# ?????
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 30

# Spring ??
spring:
  # ?????????
  mvc:
    throw-exception-if-no-handler-found: true
  # ????????
  resources:
    add-mappings: false
  # ????
  profiles:
    active: dev
  # ????
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  # ?????
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/duty?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: Zzx970331
      # ?????
      initial-size: 5
      # ???????
      min-idle: 10
      # ???????
      max-active: 20
      # ?????????????
      max-wait: 60000
      # ???????????????????????????????
      time-between-eviction-runs-millis: 60000
      # ??????????????????????
      min-evictable-idle-time-millis: 300000
      # ??????????????????????
      max-evictable-idle-time-millis: 900000
      # ??????????
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # ???????????????
        allow:
        url-pattern: /druid/*
        # ???????????
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # ?SQL??
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# MyBatis??
mybatis:
  # ???????
  typeAliasesPackage: com.bank.duty.entity
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath:mapper/**/*.xml
  # ?????????
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro??
shiro:
  web:
    enabled: false
  user:
    # ????
    loginUrl: /login
    # ????????
    unauthorizedUrl: /unauth
    # ????
    indexUrl: /index
    # ?????
    captchaEnabled: true
    # ????? math ???? char ??
    captchaType: math
  cookie:
    # ??Cookie??? ????????????
    domain:
    # ??cookie???????
    path: /
    # ??HttpOnly??
    httpOnly: true
    # ??Cookie??????????
    maxAge: 30
    # ???????????????????????main?????
    # KeyGenerator keygen = KeyGenerator.getInstance("AES"); 
    # SecretKey deskey = keygen.generateKey(); 
    # System.out.println(Base64.encodeToString(deskey.getEncoded()));
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    # Session?????-1?????????30???
    expireTime: 30
    # ??session??????????1???
    dbSyncPeriod: 1
    # ????????session?????????10??
    validationInterval: 10
    # ?????????????2???????????????????????-1????
    maxSession: 1
    # ???????/???????????????????
    kickoutAfter: false

# JWT??
jwt:
  # JWT??????
  tokenHeader: Authorization
  # JWT????????
  secret: bank-duty-secret
  # JWT???????60*60*24?
  expiration: 86400
  # JWT???????
  tokenPrefix: Bearer

# Swagger??
swagger:
  # ????swagger
  enabled: true
  # ????
  pathMapping: /

# ??XSS??
xss:
  # ????
  enabled: true
  # ?????????????
  excludes: /system/notice/*
  # ????
  urlPatterns: /system/*,/monitor/*,/api/*

# ????????
file:
  upload:
    # ????????
    basePath: /opt/bank-duty/upload
    # ?????????
    allowTypes: .jpg,.jpeg,.png,.gif,.doc,.docx,.pdf,.xls,.xlsx,.ppt,.pptx,.txt,.zip,.rar
    # ???????? 10MB
    maxSize: 10


# ????
logging:
  level:
    com.bank.duty: debug
    org.springframework: warn